.PHONY: build
build:
        ln -sf /opt/minecraft/systemd/minecraft-cleanup.service /etc/systemd/system/minecraft-cleanup.service
        ln -sf /opt/minecraft/systemd/minecraft-cleanup.timer /etc/systemd/system/minecraft-cleanup.timer
        ln -sf /opt/minecraft/systemd/minecraft.service /etc/systemd/system/minecraft.service
        ln -sf /opt/minecraft/systemd/minecraft.service.d /etc/systemd/system/minecraft.service.d
        ln -sf /opt/minecraft/systemd/minecraft.socket /etc/systemd/system/minecraft.socket
