.PHONY: install
install:
	ln -sf /opt/minecraft/shared/systemd/expire-minecraft-logs.service /etc/systemd/system/expire-minecraft-logs.service
	ln -sf /opt/minecraft/shared/systemd/expire-minecraft-logs.timer /etc/systemd/system/expire-minecraft-logs.timer
	ln -sf /opt/minecraft/shared/systemd/minecraft@.service /etc/systemd/system/minecraft@.service
	ln -sf /opt/minecraft/shared/systemd/minecraft@.service.d /etc/systemd/system/minecraft@.service.d
	ln -sf /opt/minecraft/shared/systemd/minecraft@.socket /etc/systemd/system/minecraft@.socket
